### ISSUE TITLE
Data on users' space not saved?

### ISSUE THREAD

**Issue by 130s** [tork-a/live-cd#56]
A user saved some data in /home/ubuntu/catkin_ws1. Next day he boot again from LiveUSB and the data was gone, but the Ubuntu packages (installed into /opt/ros) remained. We need to confirm whether this is true.

**Comment by k-okada** [comment]
did you check stored in reserved extra space when you create live cd?
https://help.ubuntu.com/community/Installation/FromUSBStick#Install_and_run_Startup_Disk_Creator_alias_usb-creator

--
◉ Kei Okada

**Comment by 130s** [comment]
> did you check stored in reserved extra space when you create live cd?

Yes. In fact I was not even able to turn the saving feature off (so I saw the minimum volume for saving was 1.0GB, not 0).

**Comment by 130s** [comment]
I was wrong. Data was saved in user's space too.

(1.0GB user space is pretty low for ROS workshop btw).
