### ISSUE TITLE
Jenkins check is stopped?

### ISSUE THREAD

**Issue by 130s** [tork-a/live-cd#69]
For example https://github.com/tork-a/live-cd/pull/68 I don't see test results from jenkins, which used to be printed (eg. https://github.com/tork-a/live-cd/pull/64#issuecomment-138191756).

**Comment by k-okada** [comment]
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/354/

it is working, if it seems not working you can run from http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/build?delay=0sec
