### ISSUE TITLE
/etc/resolv.conf is missing

### ISSUE THREAD

**Issue by garaemon** [tork-a/live-cd#8]
/etc/resolv.confがないので`dpkg-reconfigure resolvconf`しないとローカルドメインの
ホスト名がひけないと思われます

**Comment by wkentaro** [comment]
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/live-cd/lastSuccessfulBuild/artifact/

から2015-04-26にダウンロードしたisoファイルからディスクを作ったのですが、この問題に当たりました。
